# Generated by Django 3.0.5 on 2020-04-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(default='forgot to enter email', max_length=254)),
                ('phone_number', models.CharField(default='forgot to enter phonr number', max_length=12)),
                ('order_size', models.CharField(default='forgot to enter order size', max_length=1000)),
                ('delivery_time', models.CharField(default='take your time', max_length=1000)),
                ('Dietary_Restrictions', models.CharField(default='As per menu', max_length=1000)),
            ],
        ),
    ]
