# Generated by Django 3.0.5 on 2020-04-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200415_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskone',
            name='order_size',
        ),
    ]
