# Generated by Django 3.0.5 on 2020-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200415_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivery_time',
            field=models.CharField(choices=[('Please Select Time Slot', 'Please Select Time Slot'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('1:00 PM', '1:00 PM'), ('1:30 PM', '1:30 PM'), ('2:00 PM', '2:00 PM'), ('2:30 PM', '2:30 PM'), ('3:00 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('4:00 PM', '4:00 PM'), ('4:30 PM', '4:30 PM'), ('5:00 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('6:00 PM', '6:00 PM'), ('6:30 PM', '6:30 PM'), ('7:00 PM', '7:00 PM')], default='take your time', max_length=1000),
        ),
        migrations.AlterField(
            model_name='taskone',
            name='delivery_time',
            field=models.CharField(choices=[('Please Select Time Slot', 'Please Select Time Slot'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('1:00 PM', '1:00 PM'), ('1:30 PM', '1:30 PM'), ('2:00 PM', '2:00 PM'), ('2:30 PM', '2:30 PM'), ('3:00 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('4:00 PM', '4:00 PM'), ('4:30 PM', '4:30 PM'), ('5:00 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('6:00 PM', '6:00 PM'), ('6:30 PM', '6:30 PM'), ('7:00 PM', '7:00 PM')], default='take your time', max_length=1000),
        ),
    ]
