# Generated by Django 3.0.5 on 2020-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200415_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Delivery_Address',
            field=models.CharField(default='Not Necessary', max_length=100000),
        ),
        migrations.AddField(
            model_name='taskone',
            name='Delivery_Address',
            field=models.CharField(default='Not Necessary', max_length=100000),
        ),
        migrations.AlterField(
            model_name='taskone',
            name='phone_number',
            field=models.CharField(default='forgot to enter phone number', max_length=12),
        ),
    ]
