# Generated by Django 3.0.5 on 2020-04-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200415_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_choice',
            field=models.CharField(choices=[('Please Select Type of Order', 'Please Select Type of Order'), ('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='forgot to Select type', max_length=1000),
        ),
        migrations.AddField(
            model_name='taskone',
            name='order_choice',
            field=models.CharField(choices=[('Please Select Type of Order', 'Please Select Type of Order'), ('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='forgot to Select type', max_length=1000),
        ),
    ]
