# Generated by Django 3.0.5 on 2020-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_suppORt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delivery_time',
            field=models.CharField(default='take your time', max_length=1000),
        ),
    ]
