# Generated by Django 3.0.5 on 2020-04-09 23:43

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_suppORt', '0002_post_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
