# Generated by Django 3.0.5 on 2020-04-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_suppORt', '0003_auto_20200409_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default='forgot to enter phonr number', max_length=12),
        ),
    ]
